# GitHub Pages のビルドを使わないため、テーマもプラグインも gem で固定する。
source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "0.10.1"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-include-cache", "~> 0.2"
